'use client';

import React, { useState } from 'react';
import { Search, Code2, AlertTriangle, CheckCircle2, Copy, Check, Info } from 'lucide-react';
import AdZone from '@/components/AdZone';
import Link from 'next/link';

type Stability = 'Stable' | 'Use With Caution' | 'Fragile — Avoid';

interface Strategy {
  selector: string;
  stability: Stability;
  reason: string;
  rank: number;
}

export default function SelectorAnalyzerPage() {
  const [input, setInput] = useState('');
  const [strategies, setStrategies] = useState<Strategy[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const analyzeHtml = (html: string) => {
    if (!html.trim()) {
      setStrategies(null);
      setError(null);
      return;
    }

    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, 'text/html');
      const target = doc.body.firstElementChild;
      
      if (!target) {
        setError("Could not parse any HTML elements. Please ensure you copied the outerHTML correctly.");
        setStrategies(null);
        return;
      }

      const results: Strategy[] = [];
      const tag = target.tagName.toLowerCase();

      // 1. Data Attributes
      Array.from(target.attributes).forEach(attr => {
        if (attr.name.startsWith('data-') && attr.value) {
          results.push({
            selector: `${tag}[${attr.name}="${attr.value}"]`,
            stability: 'Stable',
            reason: `The ${attr.name} attribute is typically implemented by developers specifically for testing, state tracking, or components, making it highly stable across updates.`,
            rank: 1
          });
        }
      });

      // 2. ID
      if (target.id) {
        const isAuto = /^(ember\d+|ext-gen\d+|.*[0-9a-f]{8,}.*|\d{5,}|yui_.*)$/i.test(target.id);
        if (isAuto) {
          results.push({
            selector: `#${target.id}`,
            stability: 'Fragile — Avoid',
            reason: 'This ID appears to be auto-generated by a framework (e.g., Salesforce Lightning, Ember). It will likely change randomly on the next page load or session.',
            rank: 6
          });
        } else {
          results.push({
            selector: `#${target.id}`,
            stability: 'Stable',
            reason: 'A static, descriptive ID is the most reliable way to target an element, provided the page isn\'t a Single Page App that dynamically re-uses IDs.',
            rank: 2
          });
        }
      }

      // 3. Classes
      const validClasses = Array.from(target.classList).filter(c => {
        const isUtility = /^(p-?\d|m-?\d|flex|grid|block|inline|text-.*|bg-.*|w-\d|h-\d|z-\d|col-.*|row-.*)$/.test(c);
        const isHash = /^([a-zA-Z0-9]{8,}|css-[a-zA-Z0-9]+|sc-[a-zA-Z0-9]+)$/.test(c);
        return !isUtility && !isHash && c.length > 1;
      });

      if (validClasses.length > 0) {
        const classSelector = validClasses.map(c => `.${c}`).join('');
        results.push({
          selector: `${tag}${classSelector}`,
          stability: 'Use With Caution',
          reason: 'Classes can change if the underlying component library is updated. Ensure this class combination uniquely identifies this specific element on the screen (WalkMe stops at the first match).',
          rank: 3
        });
      }

      // 4. Semantic attributes
      ['name', 'role', 'aria-label', 'placeholder', 'type'].forEach(attr => {
        const val = target.getAttribute(attr);
        if (val) {
          results.push({
            selector: `${tag}[${attr}="${val}"]`,
            stability: 'Use With Caution',
            reason: `Targeting by the '${attr}' attribute is semantically strong, but be very careful if the value is localized—it will break for users in different languages.`,
            rank: 4
          });
        }
      });

      // 5. Exact Text Content
      const text = target.textContent?.trim();
      if (text && text.length < 50 && target.children.length === 0) {
        results.push({
          selector: `${tag}:contains("${text}")`, // jQuery syntax commonly used in WalkMe
          stability: 'Fragile — Avoid',
          reason: 'WalkMe explicitly warns against targeting by exact text. This will break instantly if the label is translated to another language, A/B tested, or slightly updated.',
          rank: 7
        });
      }

      // 6. Structural Fallback
      if (results.length === 0) {
        results.push({
          selector: tag,
          stability: 'Fragile — Avoid',
          reason: 'Using only a bare tag name or relying on a structural path (e.g. nth-child) is extremely fragile. It breaks immediately if any sibling element is added or removed.',
          rank: 8
        });
      }

      results.sort((a, b) => a.rank - b.rank);
      setStrategies(results);
      setError(null);
    } catch (err: any) {
      setError(err.message || 'Failed to parse HTML.');
      setStrategies(null);
    }
  };

  const handleCopy = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const getStabilityStyles = (stability: Stability) => {
    switch (stability) {
      case 'Stable': return 'text-green-700 bg-green-50 border-green-200 dark:text-green-400 dark:bg-green-900/20 dark:border-green-800/50';
      case 'Use With Caution': return 'text-amber-700 bg-amber-50 border-amber-200 dark:text-amber-400 dark:bg-amber-900/20 dark:border-amber-800/50';
      case 'Fragile — Avoid': return 'text-red-700 bg-red-50 border-red-200 dark:text-red-400 dark:bg-red-900/20 dark:border-red-800/50';
    }
  };

  const getStabilityIcon = (stability: Stability) => {
    switch (stability) {
      case 'Stable': return <CheckCircle2 className="w-5 h-5" />;
      case 'Use With Caution': return <AlertTriangle className="w-5 h-5" />;
      case 'Fragile — Avoid': return <AlertTriangle className="w-5 h-5" />;
    }
  };

  return (
    <div className="container mx-auto px-4 py-16 max-w-7xl flex-grow">
      
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "WalkMe Selector Robustness Analyzer",
            "operatingSystem": "Any",
            "applicationCategory": "DeveloperApplication",
            "description": "Analyze HTML to evaluate the stability and robustness of CSS/jQuery selectors for WalkMe build environments.",
            "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
          })
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
              {
                "@type": "Question",
                "name": "Why do my WalkMe selectors keep breaking?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "WalkMe selectors often break when they rely on fragile DOM structures, such as auto-generated framework IDs (like Salesforce's ext-gen), exact text content that changes with translation, or precise nth-child structural paths that shift when the underlying platform updates."
                }
              },
              {
                "@type": "Question",
                "name": "What is the difference between an ID and a Class selector?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "An ID should ideally be entirely unique on the page, making it a very strong anchor. A Class is often shared among multiple elements (e.g. 'btn-primary'). If you use a class selector, WalkMe will attach to the first matching element it finds, which might not be the one you intended."
                }
              },
              {
                "@type": "Question",
                "name": "Does this tool see my actual live website?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "No. This tool runs entirely in your browser using client-side JavaScript. It strictly analyzes the HTML string you paste in, evaluating it for known heuristic patterns. Nothing is sent to our servers, and the tool does not execute scripts or load external assets."
                }
              }
            ]
          })
        }}
      />

      <div className="text-center mb-12 relative">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-32 bg-[#A7F3D0]/40 dark:bg-[#A7F3D0]/10 blob-shape -z-10 blur-2xl"></div>
        <h1 className="text-5xl font-medium mb-4">Selector Robustness Analyzer</h1>
        <p className="text-lg opacity-70 max-w-2xl mx-auto font-sans">
          Evaluate WalkMe CSS/jQuery selectors for stability before deploying. Protect against fragile structural paths and auto-generated hashes.
        </p>
      </div>

      <div className="mb-12">
        <AdZone className="mx-auto rounded-xl overflow-hidden bg-transparent border-none max-w-4xl" type="banner" />
      </div>

      {/* Mini-Guide */}
      <div className="max-w-4xl mx-auto mb-8 bg-white/50 dark:bg-dark-card/50 border border-ink/10 dark:border-white/10 rounded-2xl p-6 font-sans">
        <h3 className="font-medium mb-3 flex items-center gap-2 text-[#059669] dark:text-[#34D399]">
          <Search className="w-5 h-5" /> How to use this tool
        </h3>
        <ol className="list-decimal pl-5 space-y-2 opacity-80 text-sm">
          <li>Right-click the target element in your browser and select <strong>Inspect</strong>.</li>
          <li>In the DevTools Elements panel, right-click the highlighted HTML node.</li>
          <li>Select <strong>Copy &gt; Copy outerHTML</strong>.</li>
          <li>Paste the code below. <strong>Important:</strong> Paste <em>only</em> the exact element you want to target, do not wrap it in parent elements!</li>
        </ol>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 font-sans min-h-[500px]">
        
        {/* Input */}
        <div className="flex flex-col bg-white dark:bg-dark-card border border-ink/10 dark:border-white/10 rounded-[2rem] overflow-hidden shadow-sm">
          <div className="p-4 border-b border-ink/5 dark:border-white/5 flex items-center justify-between bg-cream/50 dark:bg-dark-cream/50">
            <div className="flex items-center gap-2 font-medium">
              <Code2 className="w-5 h-5 text-[#34D399]" /> Target Element HTML
            </div>
            <button 
              onClick={() => { setInput(''); setStrategies(null); setError(null); }}
              className="text-sm opacity-70 hover:opacity-100 transition-opacity"
            >
              Clear
            </button>
          </div>
          <textarea
            value={input}
            onChange={(e) => { 
              setInput(e.target.value); 
              analyzeHtml(e.target.value);
            }}
            placeholder='<button id="submitBtn" data-testid="login-button" class="btn btn-primary">Login</button>'
            className="flex-grow w-full bg-transparent p-6 resize-none focus:outline-none font-mono text-sm leading-relaxed"
            spellCheck="false"
          />
          {error && (
            <div className="p-4 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 text-sm border-t border-red-100 dark:border-red-900/30">
              {error}
            </div>
          )}
        </div>

        {/* Output */}
        <div className="flex flex-col bg-white dark:bg-dark-card border border-ink/10 dark:border-white/10 rounded-[2rem] overflow-hidden shadow-sm relative">
          <div className="p-4 border-b border-ink/5 dark:border-white/5 flex items-center justify-between bg-cream/50 dark:bg-dark-cream/50">
            <div className="flex items-center gap-2 font-medium">
              <Search className="w-5 h-5 text-[#34D399]" /> Analysis Results
            </div>
          </div>

          <div className="flex-grow overflow-y-auto bg-transparent p-6 custom-scrollbar">
            {!strategies ? (
              <div className="h-full flex flex-col items-center justify-center opacity-40 text-center p-4">
                <Code2 className="w-12 h-12 mb-4 opacity-50" />
                <p>Paste an HTML element snippet to analyze potential selectors.</p>
              </div>
            ) : strategies.length > 0 ? (
              <div className="space-y-6">
                
                {/* Top Recommendation */}
                <div>
                  <h3 className="text-sm font-semibold uppercase tracking-wider opacity-60 mb-3">Top Recommendation</h3>
                  <div className={`border rounded-xl p-4 ${getStabilityStyles(strategies[0].stability)}`}>
                    <div className="flex items-start justify-between gap-4 mb-2">
                      <div className="flex items-center gap-2 font-semibold">
                        {getStabilityIcon(strategies[0].stability)}
                        {strategies[0].stability}
                      </div>
                      <button 
                        onClick={() => handleCopy(strategies[0].selector, 0)}
                        className="flex items-center gap-2 text-sm bg-white/50 dark:bg-black/20 hover:bg-white dark:hover:bg-black/40 px-3 py-1.5 rounded-lg transition-colors border border-current opacity-80 hover:opacity-100"
                      >
                        {copiedIndex === 0 ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        Copy
                      </button>
                    </div>
                    <code className="block font-mono text-lg mb-3 break-all bg-white/50 dark:bg-black/20 p-2 rounded-lg border border-current/20">
                      {strategies[0].selector}
                    </code>
                    <p className="text-sm opacity-90 leading-relaxed">
                      {strategies[0].reason}
                    </p>
                  </div>
                </div>

                {/* Alternatives */}
                {strategies.length > 1 && (
                  <div>
                    <h3 className="text-sm font-semibold uppercase tracking-wider opacity-60 mb-3 mt-8">Alternative Selectors</h3>
                    <div className="space-y-4">
                      {strategies.slice(1).map((strategy, i) => (
                        <div key={i+1} className={`border rounded-xl p-4 ${getStabilityStyles(strategy.stability)}`}>
                           <div className="flex items-start justify-between gap-4 mb-2">
                            <div className="flex items-center gap-2 font-semibold text-sm">
                              {getStabilityIcon(strategy.stability)}
                              {strategy.stability}
                            </div>
                            <button 
                              onClick={() => handleCopy(strategy.selector, i+1)}
                              className="p-1.5 rounded-md hover:bg-white/50 dark:hover:bg-black/30 transition-colors opacity-70 hover:opacity-100"
                              title="Copy selector"
                            >
                              {copiedIndex === i+1 ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                            </button>
                          </div>
                          <code className="block font-mono text-sm mb-2 break-all bg-white/30 dark:bg-black/10 p-1.5 rounded border border-current/10">
                            {strategy.selector}
                          </code>
                          <p className="text-sm opacity-80 leading-relaxed">
                            {strategy.reason}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center opacity-50 text-center">
                <AlertTriangle className="w-10 h-10 mb-3 text-red-500" />
                <p>No valid element targets found in this HTML snippet.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Usage Disclaimer */}
      <div className="max-w-4xl mx-auto mt-8">
        <div className="bg-cream/40 dark:bg-dark-cream/40 border border-ink/5 dark:border-white/5 rounded-2xl p-5 flex gap-4 text-sm font-sans items-start">
          <Info className="w-5 h-5 text-ink/40 dark:text-white/40 flex-shrink-0 mt-0.5" />
          <p className="opacity-70 leading-relaxed">
            <strong>Privacy Note:</strong> This tool parses your HTML snippet locally inside your browser. No data is ever sent to or processed on our servers, making it completely safe for enterprise platforms (SAP, Salesforce, Workday, etc). 
            <br/><br/>
            <em>Disclaimer:</em> These ratings are heuristic recommendations. An ID rated "Stable" may still break if the underlying platform uses dynamic IDs that our tool did not recognize. Always verify the selector behaves correctly inside the WalkMe Editor.
          </p>
        </div>
      </div>

      <div className="mt-20">
        <AdZone className="mx-auto rounded-xl overflow-hidden bg-transparent border-none max-w-4xl" type="banner" />
      </div>

      {/* FAQ */}
      <div className="max-w-4xl mx-auto mt-16 font-sans">
        <h2 className="text-3xl font-medium mb-8 text-center">Frequently Asked Questions</h2>
        <div className="space-y-4">
          <div className="bg-white/50 dark:bg-dark-card/50 border border-ink/10 dark:border-white/10 rounded-2xl p-6">
            <h3 className="text-xl font-medium mb-2">Why do my WalkMe selectors keep breaking?</h3>
            <p className="opacity-70 leading-relaxed">WalkMe selectors often break when they rely on fragile DOM structures. Auto-generated framework IDs (like Salesforce's <code>ext-gen</code>), exact text content that changes with translations, or precise <code>nth-child</code> structural paths that shift during platform updates are the most common culprits.</p>
          </div>
          <div className="bg-white/50 dark:bg-dark-card/50 border border-ink/10 dark:border-white/10 rounded-2xl p-6">
            <h3 className="text-xl font-medium mb-2">What is the difference between an ID and a Class selector?</h3>
            <p className="opacity-70 leading-relaxed">An ID should ideally be entirely unique on the page, making it a very strong anchor. A Class is often shared among multiple elements (e.g. <code>btn-primary</code>). If you use a class selector, WalkMe will attach to the first matching element it finds in the DOM, which might not be the one you intended.</p>
          </div>
          <div className="bg-white/50 dark:bg-dark-card/50 border border-ink/10 dark:border-white/10 rounded-2xl p-6">
            <h3 className="text-xl font-medium mb-2">Does this tool see my actual live website?</h3>
            <p className="opacity-70 leading-relaxed">No. This tool runs entirely in your browser using client-side JavaScript. It strictly analyzes the HTML string you paste in, evaluating it for known heuristic patterns. Nothing is sent to our servers, and the tool does not execute scripts or load external assets.</p>
          </div>
        </div>
      </div>

      {/* Related Tools - Fallback since it's the only tool */}
      <div className="mt-20 border-t border-ink/10 dark:border-white/10 pt-16 font-sans">
        <h2 className="text-2xl font-medium mb-8 text-center">More WalkMe Tools</h2>
        <div className="max-w-xl mx-auto text-center">
          <p className="opacity-70 mb-6">Explore the full collection of utilities built specifically for WalkMe consultants and Digital Adoption builders.</p>
          <Link href="/walkme-tools" className="inline-flex items-center justify-center bg-ink dark:bg-white text-white dark:text-ink font-medium py-3 px-8 rounded-xl transition-transform duration-150 hover:-translate-y-0.5 shadow-md">
            View All WalkMe Tools
          </Link>
        </div>
      </div>

    </div>
  );
}
